#!/bin/sh
# Static library demo

# Create static library's object file, libhello-static.o.
# I'm using the name libhello-static to clearly
# differentiate the static library from the
# dynamic library examples, but you don't need to use
# "-static" in the names of your
# object files or static libraries.

#g++ -Wall -g -c -o libhello-static.o libhello.cpp

# Create static library.

#ar rcs libhello-static.a libhello-static.o

# At this point we could just copy libhello-static.a
# somewhere else to use it.
# For demo purposes, we'll just keep the library
# in the current directory.

# Compile demo_use program file.

g++ -Wall -g -c -I../include -I../c_lib/include demo_use.cpp -o demo_use.o

# Create demo_use program; -L. causes "." to be searched during
# creation of the program.  Note that this command causes
# the relevant object file in libhello-static.a to be
# incorporated into file demo_use_static.

#g++ -Wall -g -c -I../include -I../c_lib/include demo_use.cpp -o demo_use.o
g++ -v -g -o demo_use_static demo_use.o -L. -lc_lib

# Execute the program.

./demo_use_static
